name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        git clone --depth=1 https://github.com/aergoio/secp256k1-vrf
        cd secp256k1-vrf
        ./autogen.sh
        ./configure
        make
        sudo make install
        cd ..
    - name: build
      run: make debug
    - name: install
      run: make install
    - name: test C compilation
      run: gcc examples/contract_query/contract_query.c -laergo -o contract_query
    - name: test C execution
      run: ./contract_query
    - name: test C++ compilation
      run: g++ examples/contract_query/contract_query.cpp -laergo -o contract_query_cpp
    - name: test C++ execution
      run: ./contract_query_cpp
